### ISSUE TITLE
Tool is loading

### ISSUE THREAD

**Issue by Morgoth92** [lemasato/POE-Trades-Companion#133]
The app just dont start...

**Comment by lemasato** [comment]
Hi. Make sure to update to the latest 1.13.1. This issue should have been fixed #130

**Comment by Morgoth92** [comment]
Thx you man! I really appreciate your great work. I really like your app. I just can't play without it!

**Comment by andrebardo** [comment]
In my case, it still not loading. The .exe creates a new folder on my documents, but everything is empty. This is in the logs:

`"[2018/09/02 16:50:09] PoeTrade_GetCurrencyData(createData=0): Couldn't retrieve currency data from poe.trade, falling back to json."`

**Comment by lemasato** [comment]
@andrebardo Can you try [1.13.2](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.13.2) executable?
