### ISSUE TITLE
Chat key not detected + Space as last msg character skipped(Fixed)

### ISSUE THREAD

**Issue by JYshadow** [lemasato/POE-Trades-Companion#40]
The buttons don't work now. Whenever I press a button, it doesn't automatically do the {enter} part, which means it just starts typing and open a few tabs in-game. You said "The key used to open the chat no longer defaults to ENTER: It is now automatically the same key you have set in-game." but my key to open chat is still 'enter'. Can't seem to make it work, am I mising something?

**Comment by JYshadow** [comment]
Could you by the way bring back te option to set a message, but it doesn't send it yet. 
For example: _"{enter}Sorry, not enough left, only have [I type a message]"_ and then I manually press enter, after I've typed what I wanted.
I also do this when I try to whisper someone back that I skipped. Its faster to press a button using _"@%buyerName%"_ instead of looking for his name in the sea of whispers. Maybe this could be a separate feature.

**Comment by lemasato** [comment]
Could you open your C:\Users\XXX\Documents\My Games\Path of Exile\production_Config.ini?  
I'd need to know he chat=xx line.

**Comment by JYshadow** [comment]
In my production_config.ini it is _chat=13_

**Comment by JYshadow** [comment]
Apparently, the second message does work properly. Like the party invite one. It doesn't properly do _/invite %buyerName%_, but the message after it _@%buyerName% My %itemName% listed for %itemPrice% is ready to be picked up!_ works normally.

**Comment by lemasato** [comment]
Issue fixed with 1.9.1!

The reason the second message would work is because of the {Enter} input used to send the message. Since the chat window would be opened, the second message would be able to be written and sent.

**Comment by JYshadow** [comment]
Forgot to say thanks for the previous update. But, could you perhaps make it that a {space} after the %buyerName% will also be recognised (in the write message feature)? Because when I type something after I click the button, it will stick to playername, which gets annoying sometimes.
I didn't want to make a new issue just for a just small QoL request.

**Comment by livejamie** [comment]
This is still happening on my end.

    /invite %buyerName%{Enter}@%buyerName% Come on Down! You're the next contestant on The Price Is Right! / %itemName% - %itemPrice%

No longer works.

I tried separating it into two messages

    /invite %buyerName%

    @%buyerName% Come on Down! You're the next contestant on The Price Is Right! / %itemName% - %itemPrice%

What am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/49513/25552569/fac70dd6-2c62-11e7-8b3c-1c739fcb9eb2.png)

I'm running 1.9.3.

My chat is also 13.

**Comment by lemasato** [comment]
Please provide the logs folder:  
C:\Users\XXX\Documents\AutoHotkey\POE Trades Companion\Logs

**Comment by lemasato** [comment]
1.9.4 Released:  
- The missing space at the end of a message has been fixed.
- If the chat key is invalid, the operation of sending a message will be cancelled (preventing to open random panels, use flasks or skills), and a message box will appear (to give the user directions to send me their logs).

**Comment by livejamie** [comment]
My log
[2017-04-28_22-40-45.txt](https://github.com/lemasato/POE-Trades-Companion/files/966870/2017-04-28_22-40-45.txt)
[2017-04-28_22-42-47.txt](https://github.com/lemasato/POE-Trades-Companion/files/966871/2017-04-28_22-42-47.txt)
[2017-04-28_23-25-28.txt](https://github.com/lemasato/POE-Trades-Companion/files/966872/2017-04-28_23-25-28.txt)
[changelogs.txt](https://github.com/lemasato/POE-Trades-Companion/files/966874/changelogs.txt)
[2017-04-27_09-15-52.txt](https://github.com/lemasato/POE-Trades-Companion/files/966873/2017-04-27_09-15-52.txt)

**Comment by livejamie** [comment]
Does that mean any of the messages with {Enter} in them are no longer supported? So it can't invite and send a message at the same time?

**Comment by lemasato** [comment]
It does still work.
Refer to my previous message:
You need to write your first message in the 1 slot and any other message in the 2 and 3 slots.

On the left from the area where you are writing your message, there is a number with arrows next to it. You must click on those arrows to switch between the first / second and third message.

**Comment by livejamie** [comment]
Thanks for your response.

Does that mean I have to press enter myself each message, or is there a way to have it do all at once like it was doing pre 1.9?

**Comment by lemasato** [comment]
It still sends the messages by itself.  
I'd recommend you to delete your Preferences.ini file (refer to the [Wiki](https://github.com/lemasato/POE-Trades-Companion/wiki/FAQ)) to revert back to the default settings.
Then, if the [Party Invite] invites your buyer and sends him a message, that means you've done something wrong when setting up your messages.

**Comment by lemasato** [comment]
1.9.5 released: All issues related to the chat key should now be fixed.
The last remaining one was in case the tool would be using a different account's admin rights.

@livejamie If you still need support concerning the messages, please open a new issue.
