### ISSUE TITLE
Un-Minimize/Transparency/Click-through issues

### ISSUE THREAD

**Issue by sclient** [lemasato/POE-Trades-Companion#42]
I have the checkbox on, and when I get a whisper it doesnt pop up or go to the correct opacity. v1.9.3

**Comment by lemasato** [comment]
Does it happen every time or randomly?

**Comment by sclient** [comment]
Every time so far, but my playtime has been very limited so far..

**Comment by Xebtria** [comment]
I can second this. seems to happen when I am tabbed out of the game, although not 100% of the time (I know, not reproducible means hard to investigate...), but I happened more than I'd like it lately. 1.9.4.

**Comment by sclient** [comment]
Happens either way for me.. Also 1.9.4.. Win 8.1.. Windowed fullscreen if that might matter..

**Comment by lemasato** [comment]
When the transparency issue happens, are the trade infos correctly added on the GUI?

**Comment by Xebtria** [comment]
it did not un-minimize, so I had to do that manually. but yes, the trade infos were correctly applied.

@sclient it happened to me once as well when I was ingame. it's not all the time, but it is noticeably often enough. 

@lemasato will do that check list next time I have a trade, won't be before tomorrow though, as I call it a night right now. :)

**Comment by lemasato** [comment]
What about the title bar? Does it say "Queued Trades: 1"?
The transparency (and auto minimize/un-minimize) is tied to the tabs count. If it says 1, it should definitely apply the "Active" transparency.

**Comment by Xebtria** [comment]
yes it does say that - here is a screen how it looks like:
http://i.imgur.com/O7qWHdZ.png

I also checked the slider thing you suggested, when I release the inactive slider, the actual "active" transparency is applied, also when closing the settings. but the next trade is again "inactive".

it was 100% reproducible the last 7 trades I had where I was outside of the game when the whisper came all 7 times, whereas a couple of trades before that where I was ingame it worked as expected.

**Comment by lemasato** [comment]
1.9.5 released. Can you see if the issue still occurs?

**Comment by Xebtria** [comment]
just wanted to add: it still doesn't un-minimize for some reason, but actually I don't mind as the transparency is applied correctly, so I'm fine with that.

**Comment by lemasato** [comment]
Nice. At least the transparency / click-through issues are fixed.
I'll see for the auto (un)minimize.

**Comment by sclient** [comment]
Still not un minimizing for me (I think it it minimizing at least, but Ill double check and report back) v1.10.5

**Comment by lemasato** [comment]
I have to admit I haven't looked into this lately.  
@sclient Could you try out [this beta here?](https://github.com/lemasato/POE-Trades-Companion/raw/dev/POE%20Trades%20Companion%20(Beta).exe)

- Make sure you have both "Auto Minimize" and "Auto Un-Minimize" enabled.
- Upon running the tool, you should get a message box saying "AUTO MINIMIZE".
- Head in-game, and send this message in local chat: aze @From iSellStuff: Hi, I would like to buy your SOMETHING listed for PRICE in LOCATION.
- The interface will update with the new trade request, and another message box saying "AUTO UN-MINIMIZE" should appear.

**Comment by box85** [comment]
I just updated today and I have started having all of these issues. Also my clipboard isn't updating when I get trade about 90% of the time. And when this happens I click the clipboard button and still doesn't work.
I'll try reinstalling for now :).

**Comment by lemasato** [comment]
"All of these issues" ?
Transparency / Click-through issues have been fixed. Do you get them?

Just tried out the clipboard with different whispers, works fine for me, even with quality gems. Could you share a few whispers for items that do not work?

**Comment by box85** [comment]
All of these issues was referring to the previous issues with the expanding of the window at incoming trade and click through. I deleted all the files and re-downloaded the new zip. The app works perfectly with everything again. Even with quality gems. The only difference I'm finding is that with my previous version all messages sent by the buyer after the initial ctrl-v template were saved by the "other-" section and I could read them on mouseover. These messages are no longer being displayed there. Not sure if this was intentionally removed or a bug. Thanks for the reply and the writing this app, it's an amazing addition and far more useful than anything else I've seen yet.

**Comment by lemasato** [comment]
The messages missing from the "Other" section is an issue, yes.
It will be part of the next fix.
